[package]
name = "frs-iopp"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
rand = "0.8.5"
modulo = "0.1.2"
sha2 = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
merkle = "1.11.0"
ring = "0.16"
num-bigint = "0.4"
